apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-lu4b
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vspx-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-lu4b@sha256:c25bd8e333b7bc5c36edeed119830c29b996e8df7b4e87c8cf61b3f529dec595
        name: my-nodejs
        resources: {}
status: {}
